### PR TITLE
[UPDATE] Updated project to 0.19.1

### PR DESCRIPTION
**Pull request by NullDivision**
- added some ignores to flow from node_modules
- updated Babel to version 6
- fixed kill function so it kills even if no args are present
- added message when the next message is part of current file
- separated lint functions
- fixed test failing on new version
- latest stable versions installed for all packages

### CODE REVIEW

**Comment by NullDivision** [comment]
I found an issue with default options not being translated so please hold off on this request. Sorry.

**Comment by NullDivision** [comment]
Everything should be working correctly.

Issues resolved:
- updated to version 1.19.1 (issue #35)
- process not being killed with `killFlow` option active
- tests failing
- double-line messages not displaying correctly

**Comment by charliedowler** [comment]
Hi,

Thanks a lot for doing this, much appreciated!

It all looks good to me except from the multiline errors.

Output from original code:
original code PR output
Output from your PR:
NullDivision PR output

My [flow-to-jshint](https://github.com/charliedowler/flow-to-jshint) splits new lines and splices them into a single line separated by '-' as I feel it looks much neater.

Cheers,
Charlie

**Comment by NullDivision** [comment]
I did not know that :) I'll have to take a look at the docs for `flow-to-jshint` but this is a change in the new format of `Flow` itself. I'll see what I can do about the multiple lines.

**Comment by NullDivision** [comment]
So, the issue is that the new implementation (because I'm not sure of the old one) is that errors are no longer in a single message but in multiple messages per error. `flow-to-jshint` only changes new lines to ` - ` separation.

As this is no longer the case would it be possible to merge with the new implementation and then change it to single line if that's what you want?

**Comment by NullDivision** [comment]
While going through documentation and various tests here's what I discovered:

- each file can have multiple errors
- each error can have one or more messages
- the first message contains the file being linted
- subsequent messages have a path only if referencing (eg. `[{desc: 'variable X', path: 'file.js'}, {desc: 'incompatible with type', file: ''}, {desc: 'Y', path: 'some/other/file.js'}]`)

As such I removed the whole block that tests next and previous messages because all 3 messages together make up the context as a whole, otherwise you'd end up with an error like `Variable X incompatible with` or `lib` instead of `lib Required module not found`.

**Comment by NullDivision** [comment]
Oh, and I also incremented to version 0.49.0 and updated Flow to 0.20.1.

**Comment by charliedowler** [comment]
Hi,

Thanks a lot for the PR, it should now be published.

My internet dropped out while publishing so I am not sure if it worked, tried to re-publish but can't overwrite the version number.

Let me know if you have any issues with `0.4.9`, I'll try again if needed.

Cheers,
Charlie

**Pull request merged**
