### PR TITLE
Upgrade to Flow 0.18

### PR DESCRIPTION
**Pull request by philikon**
Flow's JSON output changed somewhat. This massages it back to the old form.

### CODE REVIEW

**Comment by philikon** [comment]
Ping?

**Comment by charliedowler** [comment]
Hi,

Will test this asap and get it merged :+1: 

Thanks,
Charlie

**Comment by wanglam** [comment]
@philikon 
I try to use your version , I get a error.
Here is it:
```javascript
var { execFile, spawn } = require('child_process');
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/violin/webroot/mobileweb/gulpfile.js:27:12)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```
Could you help me solve it?

**Comment by NullDivision** [comment]
Tests are failing left and right. Also getting an error.

**Comment by NullDivision** [comment]
Hello, I've taken a look at philikon's merge and there were some failing tests as well as changes in the latest Flow package so I've fixed the tests and the failing issues and updated all packages to the latest stable version.

Merge request #38

**Pull request closed without merging**
