### PR TITLE
work on windows

### PR DESCRIPTION
**Pull request by bakesteve**
- pass in flowBin as an option (to get around facebook/flow-bin only being max/linux)
- pass in generalErrorRegEx as errors not coming back with (Fatal) < might be because win dist of flow is old? Not sure if this part is strictly needed?
- be a bit more relaxed on the check for flow. with some tests 
now matches with a word boundary, so should basically work anywhere, including in a multi line comment (like flow itself)

Added tests, but instanbul isnt running for me (another windows issue I think) - but pretty sure its all good - sorry bout that bit!

### CODE REVIEW

**Comment by charliedowler** [comment]
Hi Steve,

Thanks for the PR.

__options.flowBin__
I agree that there should be a way to override this property, not sure that an option is the best way. How about adding a `FLOW_BIN` environment variable and falling back to `require('flow-bin')`
```js
execFile(process.env.FLOW_BIN || flowBin, args, function (err, stdout, stderr) {
...
```
__options.generalErrorRegEx__
What do the error messages say when you are running on windows?

Cheers,
Charlie

**Comment by bakesteve** [comment]
yep - environment variable would work too - changed over to that.

Not sure on you're thinking on the @flow declaration (or why the tests fail..) but couldn't see any downside to picking up @flow with a word boundary `\b`?

For the errors, here is the json:
```JSON
{"passed":false,"errors":
[
{"message":[{"descr":"mergeInto.js\nRequired module not found","code":0,"path":"foo.js","line":4,"endline":4,"start":13,"end":42}]},
{"message":[{"descr":"parameter serverCol\nMissing annotation","code":0,"path":"bar.js","line":8,"endline":8,"start":23,"end":31}]},
{"message":[{"descr":"immutable.js\nRequired module not found","code":0,"path":"bar.js","line":6,"endline":6,"start":17,"end":36}]}
],"version":"33155d2065a021851151a8b96e7af7a8c2ab90de-2014-11-20-OCamlPro"}
```

looks like a really useful package, esp for hooking up with travis etc

**Comment by charliedowler** [comment]
I'm fine with this modification to the RegEx, I don't think it needs the tests though. Especially now you've simplified the RegEx.

As for the errors, I'm pretty sure those are the normal Flow errors that we show when run =>

example

Notice the `required module not found` error. Are they not logging out in the console for you? This may be another issue.

Cheers,
Charlie

**Comment by bakesteve** [comment]
Yeah – tests for such a simple regex probably overkill – and giving mocha is failing locally for me, rather hard to debug.
I’ll strip that out.

The required module is for immutable.js
Completely different issue where flow is getting thrown by finding immutable in some node_modules sub folders and failing to require it.  Get the same running flow manually, so that’s fine (annoying, but nothing to do with this)

Does seem to be a lot of issues with running all this stuff on win, but hopefully that will start getting better as gulp, npm etc get a bit more usage over on this side of the os fence

**Comment by charliedowler** [comment]
You can ignore the `node_modules` folder. Create a `.flowconfig` file in your project root, add this and it should fix your problem.
```
[ignore]
.*/node_modules/*
[include]
```

Apologise for the hassle but could you create two pull requests, one for adding the environment variable and the other for the RegEx. It will be much easier to track the history this way.

Cheers,
Charlie

**Comment by bakesteve** [comment]
replaced by #16 and #17

**Pull request closed without merging**
