### PR TITLE
Update flow-bin to 0.26.0

### PR DESCRIPTION
**Pull request by ShaneWilton**
There's quite a few optimization improvements between `0.20.1` and `0.26.0`. Locally, running flow on a small project drops from 30+ seconds to less than a second.

### CODE REVIEW

**Comment by dy-dx** [comment]
0.27.0 is available now.

**Comment by charliedowler** [comment]
Hi,

There is a tonne of things broken with this plugin and it needs a new reporter. Repurposing JSHint reporters was a bad idea.

I'm currently working on an improved version, I'll close this PR and release `5.0` soon.

Sorry for the wait.

Cheers

**Comment by charliedowler** [comment]
I just released `1.0.0` :smile:

**Comment by stephanos** [comment]
@charliedowler it works great, thanks a lot!!!

**Pull request closed without merging**
